version: '3'

services:
  mysql_java:
    image: mariadb:10.2
    container_name: mysql_java
    restart: unless-stopped
    tty: true
    ports:
      - "32345:3306"
    volumes:
      - ./database/data:/var/lib/mysql
      - ./conf.d:/etc/mysql/conf.d:ro
    environment:
      MYSQL_USER: Djony
      MYSQL_PASSWORD: 123
      MYSQL_ROOT_PASSWORD: 123
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    read_only: false